# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    base_branches: ["dev"]
