using CalcExpr.Context;
using CalcExpr.Expressions;

namespace TestCalcExpr;

public class TestCases
{
    public readonly static TestCase[] Expressions =
    {
        new TestCase(" .1", new Number(0.1)),
        new TestCase(" 0.1", new Number(0.1)),
        new TestCase(" 1.", new Number(1)),
        new TestCase(" 1", new Number(1)),
        new TestCase(" +1", new UnaryOperator("+", true, new Number(1)), new Number(1)),
        new TestCase(" -1", new UnaryOperator("-", true, new Number(1)), new Number(-1)),
        new TestCase(" !1", new UnaryOperator("!", true, new Number(1)), new Number(0)),
        new TestCase(" !0", new UnaryOperator("!", true, new Number(0)), new Number(1)),
        new TestCase(" ~2", new UnaryOperator("~", true, new Number(2)), new Number(0)),
        new TestCase(" ¬0", new UnaryOperator("¬", true, new Number(0)), new Number(1)),
        new TestCase(" 5!", new UnaryOperator("!", false, new Number(5)), new Number(120)),
        new TestCase(" 5#", new UnaryOperator("#", false, new Number(5)), new Number(2310)),
        new TestCase(" 5!! ", new UnaryOperator("!!", false, new Number(5)), new Number(15)),
        new TestCase(" 1%", new UnaryOperator("%", false, new Number(1)), new Number(0.01)),
        new TestCase("~!1 ", new UnaryOperator("~", true, new UnaryOperator("!", true, new Number(1))), new Number(1),
            new UnaryOperator("~", true, new Number(0))),
        new TestCase("2!% ", new UnaryOperator("%", false, new UnaryOperator("!", false, new Number(2))),
            new Number(0.02), new UnaryOperator("%", false, new Number(2))),
        new TestCase("-5% ", new UnaryOperator("-", true, new UnaryOperator("%", false, new Number(5))),
            new Number(-0.05), new UnaryOperator("-", true, new Number(0.05))),
        new TestCase(" 3!!!", new UnaryOperator("!", false, new UnaryOperator("!!", false, new Number(3))),
            new Number(6), new UnaryOperator("!", false, new Number(3))),
        new TestCase(" 1+2.0", new BinaryOperator("+", new Number(1), new Number(2)), new Number(3)),
        new TestCase(" 0 + 0 * 2", new BinaryOperator("+", new Number(0),
                new BinaryOperator("*", new Number(0), new Number(2))),
            new Number(0), new BinaryOperator("+", new Number(0), new Number(0))),
        new TestCase(" 1.0-2", new BinaryOperator("-", new Number(1), new Number(2)), new Number(-1)),
        new TestCase(" 2*3", new BinaryOperator("*", new Number(2), new Number(3)), new Number(6)),
        new TestCase(" 6×7", new BinaryOperator("×", new Number(6), new Number(7)), new Number(42)),
        new TestCase(" 1/2", new BinaryOperator("/", new Number(1), new Number(2)), new Number(0.5)),
        new TestCase(" 2÷2", new BinaryOperator("÷", new Number(2), new Number(2)), new Number(1)),
        new TestCase(" 2^3 ", new BinaryOperator("^", new Number(2), new Number(3)), new Number(8)),
        new TestCase("13%13", new BinaryOperator("%", new Number(13), new Number(13)), new Number(0)),
        new TestCase("12.6%13", new BinaryOperator("%", new Number(12.6), new Number(13)), new Number(12.6)),
        new TestCase("13.5%13", new BinaryOperator("%", new Number(13.5), new Number(13)), new Number(0.5)),
        new TestCase("-13%13", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13)), new Number(13)),
            new Number(0), new BinaryOperator("%", new Number(-13), new Number(13))),
        new TestCase("-12.6%13", new BinaryOperator("%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13)),
            new Number(0.4), new BinaryOperator("%", new Number(-12.6), new Number(13))),
        new TestCase("-13.5%13", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13.5)),
                new Number(13)),
            new Number(12.5), new BinaryOperator("%", new Number(-13.5), new Number(13))),
        new TestCase("13%12.6", new BinaryOperator("%", new Number(13), new Number(12.6)), new Number(0.4)),
        new TestCase("12.6%12.6", new BinaryOperator("%", new Number(12.6), new Number(12.6)), new Number(0)),
        new TestCase("13.5%12.6", new BinaryOperator("%", new Number(13.5), new Number(12.6)), new Number(0.9)),
        new TestCase("-13%12.6", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13)),
                new Number(12.6)),
            new Number(12.2), new BinaryOperator("%", new Number(-13), new Number(12.6))),
        new TestCase("-12.6%12.6", new BinaryOperator("%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(12.6)),
            new Number(0), new BinaryOperator("%", new Number(-12.6), new Number(12.6))),
        new TestCase("-13.5%12.6", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13.5)),
                new Number(12.6)),
            new Number(11.7), new BinaryOperator("%", new Number(-13.5), new Number(12.6))),
        new TestCase("13%13.5", new BinaryOperator("%", new Number(13), new Number(13.5)), new Number(13)),
        new TestCase("12.6%13.5", new BinaryOperator("%", new Number(12.6), new Number(13.5)), new Number(12.6)),
        new TestCase("13.5%13.5", new BinaryOperator("%", new Number(13.5), new Number(13.5)), new Number(0)),
        new TestCase("-13%13.5", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13)),
                new Number(13.5)),
            new Number(0.5), new BinaryOperator("%", new Number(-13), new Number(13.5))),
        new TestCase("-12.6%13.5", new BinaryOperator("%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13.5)),
            new Number(0.9), new BinaryOperator("%", new Number(-12.6), new Number(13.5))),
        new TestCase("-13.5%13.5", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13.5)), new Number(13.5)),
            new Number(0), new BinaryOperator("%", new Number(-13.5), new Number(13.5))),
        new TestCase("13%(-13)", new BinaryOperator("%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(0), new BinaryOperator("%", new Number(13), new Parentheses(new Number(-13))),
            new BinaryOperator("%", new Number(13), new Number(-13))),
        new TestCase("12.6%(-13)", new BinaryOperator("%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(12.6), new BinaryOperator("%", new Number(12.6), new Parentheses(new Number(-13))),
            new BinaryOperator("%", new Number(12.6), new Number(-13))),
        new TestCase("-13%(-13)", new BinaryOperator("%", new UnaryOperator("-", true, new Number(13)),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(0), new BinaryOperator("%", new Number(-13),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new BinaryOperator("%", new Number(-13), new Parentheses(new Number(-13))),
            new BinaryOperator("%", new Number(-13), new Number(-13))),
        new TestCase("-12.6%(-13)", new BinaryOperator("%", new UnaryOperator("-", true, new Number(12.6)),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(0.4), new BinaryOperator("%", new Number(-12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new BinaryOperator("%", new Number(-12.6), new Parentheses(new Number(-13))),
            new BinaryOperator("%", new Number(-12.6), new Number(-13))),
        new TestCase("13%(-12.6)", new BinaryOperator("%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0.4), new BinaryOperator("%", new Number(13), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%", new Number(13), new Number(-12.6))),
        new TestCase("12.6%(-12.6)", new BinaryOperator("%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0), new BinaryOperator("%", new Number(12.6), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%", new Number(12.6), new Number(-12.6))),
        new TestCase("13.5%(-12.6)", new BinaryOperator("%", new Number(13.5),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0.9), new BinaryOperator("%", new Number(13.5), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%", new Number(13.5), new Number(-12.6))),
        new TestCase("13%(-13.5)", new BinaryOperator("%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(13), new BinaryOperator("%", new Number(13), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%", new Number(13), new Number(-13.5))),
        new TestCase("12.6%(-13.5)", new BinaryOperator("%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(12.6), new BinaryOperator("%", new Number(12.6), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%", new Number(12.6), new Number(-13.5))),
        new TestCase("13.5%(-13.5)", new BinaryOperator("%", new Number(13.5),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(0), new BinaryOperator("%", new Number(13.5), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%", new Number(13.5), new Number(-13.5))),
        new TestCase("13%%13", new BinaryOperator("%%", new Number(13), new Number(13)), new Number(0)),
        new TestCase("12.6%%13", new BinaryOperator("%%", new Number(12.6), new Number(13)), new Number(12.6)),
        new TestCase("13.5%%13", new BinaryOperator("%%", new Number(13.5), new Number(13)), new Number(0.5)),
        new TestCase("-13%%13", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)), new Number(13)),
            new Number(0), new BinaryOperator("%%", new Number(-13), new Number(13))),
        new TestCase("-12.6%%13", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13)),
            new Number(-12.6), new BinaryOperator("%%", new Number(-12.6), new Number(13))),
        new TestCase("-13.5%%13", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13.5)),
                new Number(13)),
            new Number(-0.5), new BinaryOperator("%%", new Number(-13.5), new Number(13))),
        new TestCase("13%%12.6", new BinaryOperator("%%", new Number(13), new Number(12.6)), new Number(0.4)),
        new TestCase("12.6%%12.6", new BinaryOperator("%%", new Number(12.6), new Number(12.6)), new Number(0)),
        new TestCase("13.5%%12.6", new BinaryOperator("%%", new Number(13.5), new Number(12.6)), new Number(0.9)),
        new TestCase("-13%%12.6", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)),
                new Number(12.6)),
            new Number(-0.4), new BinaryOperator("%%", new Number(-13), new Number(12.6))),
        new TestCase("-12.6%%12.6", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(12.6)),
            new Number(0), new BinaryOperator("%%", new Number(-12.6), new Number(12.6))),
        new TestCase("-13.5%%12.6", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13.5)),
                new Number(12.6)),
            new Number(-0.9), new BinaryOperator("%%", new Number(-13.5), new Number(12.6))),
        new TestCase("13%%13.5", new BinaryOperator("%%", new Number(13), new Number(13.5)), new Number(13)),
        new TestCase("12.6%%13.5", new BinaryOperator("%%", new Number(12.6), new Number(13.5)), new Number(12.6)),
        new TestCase("13.5%%13.5", new BinaryOperator("%%", new Number(13.5), new Number(13.5)), new Number(0)),
        new TestCase("-13%%13.5", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)),
                new Number(13.5)),
            new Number(-13), new BinaryOperator("%%", new Number(-13), new Number(13.5))),
        new TestCase("-12.6%%13.5", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13.5)),
            new Number(-12.6), new BinaryOperator("%%", new Number(-12.6), new Number(13.5))),
        new TestCase("-13.5%%13.5", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13.5)),
                new Number(13.5)),
            new Number(0), new BinaryOperator("%%", new Number(-13.5), new Number(13.5))),
        new TestCase("13%%(-13)", new BinaryOperator("%%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(0), new BinaryOperator("%%", new Number(13), new Parentheses(new Number(-13))),
            new BinaryOperator("%%", new Number(13), new Number(-13))),
        new TestCase("12.6%%(-13)", new BinaryOperator("%%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(12.6), new BinaryOperator("%%", new Number(12.6), new Parentheses(new Number(-13))),
                new BinaryOperator("%%", new Number(12.6), new Number(-13))),
        new TestCase("-13%%(-13)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(0), new BinaryOperator("%%", new Number(-13),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new BinaryOperator("%%", new Number(-13), new Parentheses(new Number(-13))),
            new BinaryOperator("%%", new Number(-13), new Number(-13))),
        new TestCase("-12.6%%(-13)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(-12.6), new BinaryOperator("%%", new Number(-12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new BinaryOperator("%%", new Number(-12.6), new Parentheses(new Number(-13))),
            new BinaryOperator("%%", new Number(-12.6), new Number(-13))),
        new TestCase("13%%(-12.6)", new BinaryOperator("%%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0.4), new BinaryOperator("%%", new Number(13), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(13), new Number(-12.6))),
        new TestCase("12.6%%(-12.6)", new BinaryOperator("%%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0), new BinaryOperator("%%", new Number(12.6), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(12.6), new Number(-12.6))),
        new TestCase("13.5%%(-12.6)", new BinaryOperator("%%", new Number(13.5),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0.9), new BinaryOperator("%%", new Number(13.5), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(13.5), new Number(-12.6))),
        new TestCase("-13%%(-12.6)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(-0.4), new BinaryOperator("%%", new Number(-13),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new BinaryOperator("%%", new Number(-13), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(-13), new Number(-12.6))),
        new TestCase("-12.6%%(-12.6)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(0), new BinaryOperator("%%", new Number(-12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new BinaryOperator("%%", new Number(-12.6), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(-12.6), new Number(-12.6))),
        new TestCase("-13.5%%(-12.6)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13.5)),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new Number(-0.9), new BinaryOperator("%%", new Number(-13.5),
                new Parentheses(new UnaryOperator("-", true, new Number(12.6)))),
            new BinaryOperator("%%", new Number(-13.5), new Parentheses(new Number(-12.6))),
            new BinaryOperator("%%", new Number(-13.5), new Number(-12.6))),
        new TestCase("13%%(-13.5)", new BinaryOperator("%%", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(13), new BinaryOperator("%%", new Number(13), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(13), new Number(-13.5))),
        new TestCase("12.6%%(-13.5)", new BinaryOperator("%%", new Number(12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(12.6), new BinaryOperator("%%", new Number(12.6), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(12.6), new Number(-13.5))),
        new TestCase("13.5%%(-13.5)", new BinaryOperator("%%", new Number(13.5),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(0), new BinaryOperator("%%", new Number(13.5), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(13.5), new Number(-13.5))),
        new TestCase("-13%%(-13.5)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13)),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(-13), new BinaryOperator("%%", new Number(-13),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new BinaryOperator("%%", new Number(-13), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(-13), new Number(-13.5))),
        new TestCase("-12.6%%(-13.5)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(12.6)),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(-12.6), new BinaryOperator("%%", new Number(-12.6),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new BinaryOperator("%%", new Number(-12.6), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(-12.6), new Number(-13.5))),
        new TestCase("-13.5%%(-13.5)", new BinaryOperator("%%", new UnaryOperator("-", true, new Number(13.5)),
                new Parentheses(new UnaryOperator("-", true, new Number(13.5)))),
            new Number(0), new BinaryOperator("%%", new Number(-13.5), new Parentheses(new UnaryOperator("-", true,
                new Number(13.5)))),
            new BinaryOperator("%%", new Number(-13.5), new Parentheses(new Number(-13.5))),
            new BinaryOperator("%%", new Number(-13.5), new Number(-13.5))),
        new TestCase("12.6//13", new BinaryOperator("//", new Number(12.6), new Number(13)), new Number(0)),
        new TestCase("13.5//13", new BinaryOperator("//", new Number(13.5), new Number(13)), new Number(1)),
        new TestCase("-13//13", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)), new Number(13)),
            new Number(-1), new BinaryOperator("//", new Number(-13), new Number(13))),
        new TestCase("-12.6//13", new BinaryOperator("//", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13)),
            new Number(-1), new BinaryOperator("//", new Number(-12.6), new Number(13))),
        new TestCase("-13.5//13", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13.5)),
                new Number(13)),
            new Number(-2), new BinaryOperator("//", new Number(-13.5), new Number(13))),
        new TestCase("13//12.6", new BinaryOperator("//", new Number(13), new Number(12.6)), new Number(1)),
        new TestCase("13.5//12.6", new BinaryOperator("//", new Number(13.5), new Number(12.6)), new Number(1)),
        new TestCase("-13//12.6", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)),
                new Number(12.6)),
            new Number(-2), new BinaryOperator("//", new Number(-13), new Number(12.6))),
        new TestCase("-13.5//12.6", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13.5)),
                new Number(12.6)),
            new Number(-2), new BinaryOperator("//", new Number(-13.5), new Number(12.6))),
        new TestCase("13//13.5", new BinaryOperator("//", new Number(13), new Number(13.5)), new Number(0)),
        new TestCase("12.6//13.5", new BinaryOperator("//", new Number(12.6), new Number(13.5)), new Number(0)),
        new TestCase("-13//13.5", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)),
                new Number(13.5)),
            new Number(-1), new BinaryOperator("//", new Number(-13), new Number(13.5))),
        new TestCase("-12.6//13.5", new BinaryOperator("//", new UnaryOperator("-", true, new Number(12.6)),
                new Number(13.5)),
            new Number(-1), new BinaryOperator("//", new Number(-12.6), new Number(13.5))),
        new TestCase("-13.5//13.5", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13.5)),
                new Number(13.5)),
            new Number(-1), new BinaryOperator("//", new Number(-13.5), new Number(13.5))),
        new TestCase("13//(-13)", new BinaryOperator("//", new Number(13),
                new Parentheses(new UnaryOperator("-", true, new Number(13)))),
            new Number(-1), new BinaryOperator("//", new Number(13), new Parentheses(new Number(-13))),
            new BinaryOperator("//", new Number(13), new Number(-13))),
        new TestCase("12.6//-13", new BinaryOperator("//", new Number(12.6), new UnaryOperator("-", true,
                new Number(13))),
            new Number(0), new BinaryOperator("//", new Number(12.6), new Number(-13))),
        new TestCase("-13//-13", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)),
                new UnaryOperator("-", true, new Number(13))),
            new Number(1), new BinaryOperator("//", new Number(-13), new UnaryOperator("-", true, new Number(13))),
            new BinaryOperator("//", new Number(-13), new Number(-13))),
        new TestCase("-12.6//-13", new BinaryOperator("//", new UnaryOperator("-", true, new Number(12.6)),
                new UnaryOperator("-", true, new Number(13))),
            new Number(1), new BinaryOperator("//", new Number(-12.6), new UnaryOperator("-", true, new Number(13))),
            new BinaryOperator("//", new Number(-12.6), new Number(-13))),
        new TestCase("13//-12.6", new BinaryOperator("//", new Number(13),
                new UnaryOperator("-", true, new Number(12.6))),
            new Number(-1), new BinaryOperator("//", new Number(13), new Number(-12.6))),
        new TestCase("13.5//-12.6", new BinaryOperator("//", new Number(13.5),
                new UnaryOperator("-", true, new Number(12.6))),
            new Number(-1), new BinaryOperator("//", new Number(13.5), new Number(-12.6))),
        new TestCase("-13//-12.6", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)),
                new UnaryOperator("-", true, new Number(12.6))),
            new Number(2), new BinaryOperator("//", new Number(-13), new UnaryOperator("-", true, new Number(12.6))),
            new BinaryOperator("//", new Number(-13), new Number(-12.6))),
        new TestCase("-13.5//-12.6", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13.5)),
                new UnaryOperator("-", true, new Number(12.6))),
            new Number(2), new BinaryOperator("//", new Number(-13.5), new UnaryOperator("-", true, new Number(12.6))),
            new BinaryOperator("//", new Number(-13.5), new Number(-12.6))),
        new TestCase("13//-13.5", new BinaryOperator("//", new Number(13),
                new UnaryOperator("-", true, new Number(13.5))),
            new Number(0), new BinaryOperator("//", new Number(13), new Number(-13.5))),
        new TestCase("12.6//-13.5", new BinaryOperator("//", new Number(12.6),
                new UnaryOperator("-", true, new Number(13.5))),
            new Number(0), new BinaryOperator("//", new Number(12.6), new Number(-13.5))),
        new TestCase("-13//-13.5", new BinaryOperator("//", new UnaryOperator("-", true, new Number(13)),
                new UnaryOperator("-", true, new Number(13.5))),
            new Number(1), new BinaryOperator("//", new Number(-13), new UnaryOperator("-", true, new Number(13.5))),
            new BinaryOperator("//", new Number(-13), new Number(-13.5))),
        new TestCase("-12.6//-13.5", new BinaryOperator("//", new UnaryOperator("-", true, new Number(12.6)),
                new UnaryOperator("-", true, new Number(13.5))),
            new Number(1), new BinaryOperator("//", new Number(-12.6), new UnaryOperator("-", true, new Number(13.5))),
            new BinaryOperator("//", new Number(-12.6), new Number(-13.5))),
        new TestCase(" 1&&2", new BinaryOperator("&&", new Number(1), new Number(2)), new Number(1)),
        new TestCase(" 1&&0", new BinaryOperator("&&", new Number(1), new Number(0)), new Number(0)),
        new TestCase(" 0∧1", new BinaryOperator("∧", new Number(0), new Number(1)), new Number(0)),
        new TestCase(" 0∧0", new BinaryOperator("∧", new Number(0), new Number(0)), new Number(0)),
        new TestCase(" 1||2", new BinaryOperator("||", new Number(1), new Number(2)), new Number(1)),
        new TestCase(" 0||2", new BinaryOperator("||", new Number(0), new Number(2)), new Number(1)),
        new TestCase(" 1 ∨0", new BinaryOperator("∨", new Number(1), new Number(0)), new Number(1)),
        new TestCase(" 0 ∨0", new BinaryOperator("∨", new Number(0), new Number(0)), new Number(0)),
        new TestCase(" 1 ⊕5", new BinaryOperator("⊕", new Number(1), new Number(5)), new Number(0)),
        new TestCase(" 4 ⊕0", new BinaryOperator("⊕", new Number(4), new Number(0)), new Number(1)),
        new TestCase(" 0 ⊕2", new BinaryOperator("⊕", new Number(0), new Number(2)), new Number(1)),
        new TestCase(" 0 ⊕0", new BinaryOperator("⊕", new Number(0), new Number(0)), new Number(0)),
        new TestCase(" 1 ==2", new BinaryOperator("==", new Number(1), new Number(2)), new Number(0)),
        new TestCase(" pi ==π", new BinaryOperator("==", new Constant("pi"), new Constant("π")), new Number(1),
            new BinaryOperator("==", new Number(Math.PI), new Constant("π")),
            new BinaryOperator("==", new Number(Math.PI), new Number(Math.PI))),
        new TestCase(" 1 !=2", new BinaryOperator("!=", new Number(1), new Number(2)), new Number(1)),
        new TestCase(" infinity ≠inf", new BinaryOperator("≠", new Constant("infinity"), new Constant("inf")),
            new Number(0)),
        new TestCase(" 2 <>2", new BinaryOperator("<>", new Number(2), new Number(2)), new Number(0)),
        new TestCase(" 1 <2", new BinaryOperator("<", new Number(1), new Number(2)), new Number(1)),
        new TestCase(" 1>2", new BinaryOperator(">", new Number(1), new Number(2)), new Number(0)),
        new TestCase(" 1 <=2", new BinaryOperator("<=", new Number(1), new Number(2)), new Number(1)),
        new TestCase(" 1 ≤1", new BinaryOperator("≤", new Number(1), new Number(1)), new Number(1)),
        new TestCase(" 1 >=2", new BinaryOperator(">=", new Number(1), new Number(2)), new Number(0)),
        new TestCase(" 2 ≥2", new BinaryOperator("≥", new Number(2), new Number(2)), new Number(1)),
        new TestCase(" 1+2-3*4  /5^7&&8||9⊕10==11", new BinaryOperator("||", new BinaryOperator("&&",
            new BinaryOperator("-", new BinaryOperator("+", new Number(1), new Number(2)), new BinaryOperator("/",
                new BinaryOperator("*", new Number(3), new Number(4)), new BinaryOperator("^", new Number(5),
                    new Number(7)))), new Number(8)), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==",
                new Number(10), new Number(11)))),
            new Number(1), new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("-", new Number(3),
                new BinaryOperator("/", new BinaryOperator("*", new Number(3), new Number(4)), new BinaryOperator("^",
                    new Number(5), new Number(7)))), new Number(8)),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("-", new Number(3),
                    new BinaryOperator("/", new Number(12), new BinaryOperator("^", new Number(5), new Number(7)))),
                new Number(8)), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10),
                    new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("-", new Number(3),
                new BinaryOperator("/", new Number(12), new Number(78125))), new Number(8)), new BinaryOperator("⊕",
                    new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("-", new Number(3),
                    new Number((double)12 / 78125)), new Number(8)), new BinaryOperator("⊕", new Number(9),
                new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new Number(3 - ((double)12 / 78125)), new Number(8)),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new Number(1), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==",
                new Number(10), new Number(11)))),
            new BinaryOperator("||", new Number(1), new BinaryOperator("⊕", new Number(9), new Number(0))),
            new BinaryOperator("||", new Number(1), new Number(1)),
            new Number(1)),
        new TestCase("+1+-2.0", new BinaryOperator("+", new UnaryOperator("+", true, new Number(1)),
                new UnaryOperator("-", true, new Number(2))),
            new Number(-1), new BinaryOperator("+", new Number(1), new UnaryOperator("-", true, new Number(2))),
            new BinaryOperator("+", new Number(1), new Number(-2)), new Number(-1)),
        new TestCase("1.0!-2%", new BinaryOperator("-", new UnaryOperator("!", false, new Number(1)),
                new UnaryOperator("%", false, new Number(2))),
            new Number(0.98), new BinaryOperator("-", new Number(1), new UnaryOperator("%", false, new Number(2))),
            new BinaryOperator("-", new Number(1), new Number(0.02)), new Number(0.98)),
        new TestCase("!¬2*-  +3", new BinaryOperator("*", new UnaryOperator("!", true, new UnaryOperator("¬", true,
                new Number(2))), new UnaryOperator("-", true, new UnaryOperator("+", true, new Number(3)))),
            new Number(-3), new BinaryOperator("*", new UnaryOperator("!", true, new Number(0)),
                new UnaryOperator("-", true, new UnaryOperator("+", true, new Number(3)))),
            new BinaryOperator("*", new Number(1), new UnaryOperator("-", true, new UnaryOperator("+", true,
                new Number(3)))), new BinaryOperator("*", new Number(1), new UnaryOperator("-", true, new Number(3))),
            new BinaryOperator("*", new Number(1), new Number(-3))),
        new TestCase("1%%/2!!", new BinaryOperator("/", new UnaryOperator("%", false, new UnaryOperator("%", false,
                new Number(1))), new UnaryOperator("!!", false, new Number(2))),
            new Number(0.00005), new BinaryOperator("/", new UnaryOperator("%", false, new Number(0.01)),
                new UnaryOperator("!!", false, new Number(2))),
            new BinaryOperator("/", new Number(0.0001), new UnaryOperator("!!", false, new Number(2))),
            new BinaryOperator("/", new Number(0.0001), new Number(2)), new Number(0.00005)),
        new TestCase("-13!%(!12)%", new BinaryOperator("%", new UnaryOperator("-", true, new UnaryOperator("!", false,
                new Number(13))), new UnaryOperator("%", false, new Parentheses(new UnaryOperator("!", true,
                    new Number(12))))),
            new Number(411680.94),
            new BinaryOperator("%", new UnaryOperator("-", true, new Number(6227020800)), new UnaryOperator("%", false,
                new Parentheses(new UnaryOperator("!", true, new Number(12))))),
            new BinaryOperator("%", new Number(-6227020800), new UnaryOperator("%", false, new Parentheses(
                new UnaryOperator("!", true, new Number(12))))),
            new BinaryOperator("%", new Number(-6227020800), new UnaryOperator("%", false, new Parentheses(
                new Number(176214841)))),
            new BinaryOperator("%", new Number(-6227020800), new UnaryOperator("%", false, new Number(176214841))),
            new BinaryOperator("%", new Number(-6227020800), new Number(1762148.41))),
        new TestCase("1+((2-τ)*(4 /-pi))^7&& abc_1||9⊕10==  11", new BinaryOperator("||", new BinaryOperator("&&",
            new BinaryOperator("+", new Number(1), new BinaryOperator("^", new Parentheses(new BinaryOperator("*",
                new Parentheses(new BinaryOperator("-", new Number(2), new Constant("τ"))), new Parentheses(
                    new BinaryOperator("/", new Number(4), new UnaryOperator("-", true, new Constant("pi")))))),
                new Number(7))), new Variable("abc_1")), new BinaryOperator("⊕", new Number(9),
                    new BinaryOperator("==", new Number(10), new Number(11)))),
            new Number(1), new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                new BinaryOperator("^", new Parentheses(new BinaryOperator("*", new Parentheses(new BinaryOperator("-",
                    new Number(2), new Number(Math.Tau))), new Parentheses(new BinaryOperator("/", new Number(4),
                        new UnaryOperator("-", true, new Constant("pi")))))), new Number(7))), new Variable("abc_1")),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                    new BinaryOperator("^", new Parentheses(new BinaryOperator("*", new Parentheses(
                        new Number(2 - Math.Tau)), new Parentheses(new BinaryOperator("/", new Number(4),
                            new UnaryOperator("-", true, new Constant("pi")))))), new Number(7))), new Variable("abc_1")),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                new BinaryOperator("^", new Parentheses( new BinaryOperator("*", new Number(2 - Math.Tau),
                    new Parentheses(new BinaryOperator("/", new Number(4), new UnaryOperator("-", true,
                        new Constant("pi")))))), new Number(7))), new Variable("abc_1")), new BinaryOperator("⊕",
                            new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                    new BinaryOperator("^", new Parentheses( new BinaryOperator("*", new Number(2 - Math.Tau),
                        new Parentheses(new BinaryOperator("/", new Number(4), new UnaryOperator("-", true,
                            new Number(Math.PI)))))), new Number(7))), new Variable("abc_1")),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                new BinaryOperator("^", new Parentheses(new BinaryOperator("*", new Number(2 - Math.Tau),
                    new Parentheses(new BinaryOperator("/", new Number(4), new Number(-Math.PI))))), new Number(7))),
                new Variable("abc_1")), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10),
                    new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                    new BinaryOperator("^", new Parentheses(new BinaryOperator("*", new Number(2 - Math.Tau),
                        new Parentheses(new Number(4 / -Math.PI)))), new Number(7))), new Variable("abc_1")),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                new BinaryOperator("^", new Parentheses(new BinaryOperator("*", new Number(2 - Math.Tau),
                    new Number(4 / -Math.PI))), new Number(7))), new Variable("abc_1")), new BinaryOperator("⊕",
                        new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                    new BinaryOperator("^", new Parentheses(new Number((8 - 4 * Math.Tau) / -Math.PI)), new Number(7))),
                new Variable("abc_1")), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10),
                    new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                    new BinaryOperator("^", new Number((8 - 4 * Math.Tau) / -Math.PI), new Number(7))),
                new Variable("abc_1")), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10),
                    new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&", new BinaryOperator("+", new Number(1),
                new Number(Math.Pow((8 - 4 * Math.Tau) / -Math.PI, 7))), new Variable("abc_1")), new BinaryOperator("⊕",
                    new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&",
                    new Number(1 + Math.Pow((8 - 4 * Math.Tau) / -Math.PI, 7)), new Variable("abc_1")),
                new BinaryOperator("⊕", new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new BinaryOperator("&&",
                new Number(1 + Math.Pow((8 - 4 * Math.Tau) / -Math.PI, 7)), new Number(1)), new BinaryOperator("⊕",
                    new Number(9), new BinaryOperator("==", new Number(10), new Number(11)))),
            new BinaryOperator("||", new Number(1), new BinaryOperator("⊕", new Number(9), new BinaryOperator("==",
                new Number(10), new Number(11)))),
            new BinaryOperator("||", new Number(1), new BinaryOperator("⊕", new Number(9), new Number(0))),
            new BinaryOperator("||", new Number(1), new Number(1))),
        new TestCase("∞", new Constant("∞")),
        new TestCase("inf", new Constant("inf")),
        new TestCase("infinity ", new Constant("infinity")),
        new TestCase("-∞", new UnaryOperator("-", true, new Constant("∞")), new Constant("-∞")),
        new TestCase("-inf", new UnaryOperator("-", true, new Constant("inf")), new Constant("-inf")),
        new TestCase("-infinity ", new UnaryOperator("-", true, new Constant("infinity")), new Constant("-infinity")),
        new TestCase("π", new Constant("π"), new Number(Math.PI)),
        new TestCase("pi", new Constant("pi"), new Number(Math.PI)),
        new TestCase("τ", new Constant("τ"), new Number(Math.Tau)),
        new TestCase("tau", new Constant("tau"), new Number(Math.Tau)),
        new TestCase("e", new Constant("e"), new Number(Math.E)),
        new TestCase("true", new Constant("true"), new Number(1)),
        new TestCase("false", new Constant("false"), new Number(0)),
        new TestCase("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz ",
            new Variable("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"), new Number(2)),
        new TestCase("ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσςΤτΥυΦφΧχΨψΩω",
            new Variable("ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσςΤτΥυΦφΧχΨψΩω"), new Number(3)),
        new TestCase("abc_123", new Variable("abc_123"), new Number(4)),
        new TestCase("αβγ_123", new Variable("αβγ_123"), new Number(5)),
        new TestCase("abcd_αβγ_xyz", new Variable("abcd_αβγ_xyz"), new Number(6)),
        new TestCase("abcd_αβγ_xyz=3", new BinaryOperator("=", new Variable("abcd_αβγ_xyz"), new Number(3)),
            new Number(3)),
        new TestCase("abcd_αβγ_xyz=π", new BinaryOperator("=", new Variable("abcd_αβγ_xyz"), new Constant("π")),
            new Number(Math.PI)),
        new TestCase("abcd_αβγ_xyz=inf", new BinaryOperator("=", new Variable("abcd_αβγ_xyz"), new Constant("inf")),
            new Constant("inf")),
        new TestCase("--1", new UnaryOperator("--", true, new Number(1)), new Number(0)),
        new TestCase("++1", new UnaryOperator("++", true, new Number(1)), new Number(2)),
        new TestCase("1--", new UnaryOperator("--", false, new Number(1)), new Number(1)),
        new TestCase("1++", new UnaryOperator("++", false, new Number(1)), new Number(1)),
        new TestCase("---1", new UnaryOperator("--", true, new UnaryOperator("-", true, new Number(1))),
            new Number(-2), new UnaryOperator("--", true, new Number(-1))),
        new TestCase("+++1", new UnaryOperator("++", true, new UnaryOperator("+", true, new Number(1))), new Number(2),
            new UnaryOperator("++", true, new Number(1))),
        new TestCase("(x=3)-x", new BinaryOperator("-", new Parentheses(new BinaryOperator("=", new Variable("x"),
                new Number(3))), new Variable("x")),
            new Number(0), new BinaryOperator("-", new Parentheses(new Number(3)), new Variable("x")),
            new BinaryOperator("-", new Number(3), new Variable("x")),
            new BinaryOperator("-", new Number(3), new Number(3))),
        new TestCase("p(3)", new FunctionCall("p", new IExpression[] { new Number(3) }), new Number(4)),
        new TestCase("f(3)", new FunctionCall("f", new IExpression[] { new Number(3) }), new Number(3)),
        new TestCase("g(1, 2, 3)", new FunctionCall("g",
                new IExpression[] { new Number(1), new Number(2), new Number(3) }),
            new Number(5)),
        new TestCase("g(abc_1, 2, 3+4*1)", new FunctionCall("g", new IExpression[] { new Variable("abc_1"),
                new Number(2), new BinaryOperator("+", new Number(3), new BinaryOperator("*", new Number(4),
                    new Number(1))) }),
            new Number(9), new FunctionCall("g", new IExpression[] { new Number(1), new Number(2),
                new BinaryOperator("+", new Number(3), new BinaryOperator("*", new Number(4), new Number(1))) }),
            new FunctionCall("g", new IExpression[] { new Number(1), new Number(2),
                new BinaryOperator("+", new Number(3), new Number(4)) }),
            new FunctionCall("g", new IExpression[] { new Number(1), new Number(2), new Number(7) })),
        new TestCase("is_num(3)", new FunctionCall("is_num", new IExpression[] { new Number(3) }), new Number(1)),
        new TestCase("is_num(infinity)", new FunctionCall("is_num", new IExpression[] { new Constant("infinity") }),
            new Number(0)),
        new TestCase("is_num(3+4)", new FunctionCall("is_num",
            new IExpression[] { new BinaryOperator("+", new Number(3), new Number(4)) }), new Number(0)),
    };

    public readonly static Dictionary<string, IExpression> Variables = new Dictionary<string, IExpression>()
    {
        { "abc_1", new Number(1) },
        { "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz", new Number(2) },
        { "ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσςΤτΥυΦφΧχΨψΩω", new Number(3) },
        { "abc_123", new Number(4) },
        { "αβγ_123", new Number(5) },
        { "abcd_αβγ_xyz", new Number(6) },
        { "p", new Function(P) },
    };

    public readonly static Dictionary<string, Function> Functions = new Dictionary<string, Function>()
    {
        { "f", new Function(F) },
        { "g", new Function(G) },
        { "is_num", new Function(IsNum) },
    };

    public static IExpression F(IExpression x)
        => x;

    public static IExpression G(IExpression m, IExpression x, IExpression b)
        => new BinaryOperator("+", new BinaryOperator("*", m, x), b).Evaluate();

    public static IExpression IsNum(IExpression x, ExpressionContext _)
        => x is Number ? Constant.TRUE : Constant.FALSE;

    public static IExpression P(IExpression x)
        => x is Number n ? new Number(n.Value + 1) : Constant.UNDEFINED;
}

public readonly struct TestCase
{
    public readonly string ExpressionString;
    public readonly IExpression Parsed;
    public readonly IExpression Evaluated;
    public readonly IExpression[] StepEvaluated;

    public TestCase(string expression_string, IExpression parsed, IExpression? evaluated = null,
        params IExpression[] step_evaluated)
    {
        ExpressionString = expression_string;
        Parsed = parsed;
        Evaluated = evaluated ?? Parsed;
        StepEvaluated = (step_evaluated ?? Array.Empty<IExpression>()).Append(Evaluated).ToArray();
    }
}
